import 'package:flutter_highlighting/themes/a11y-dark.dart';
import 'package:flutter_highlighting/themes/a11y-light.dart';
import 'package:flutter_highlighting/themes/agate.dart';
import 'package:flutter_highlighting/themes/an-old-hope.dart';
import 'package:flutter_highlighting/themes/androidstudio.dart';
import 'package:flutter_highlighting/themes/arduino-light.dart';
import 'package:flutter_highlighting/themes/arta.dart';
import 'package:flutter_highlighting/themes/ascetic.dart';
import 'package:flutter_highlighting/themes/atelier-cave-dark.dart';
import 'package:flutter_highlighting/themes/atelier-cave-light.dart';
import 'package:flutter_highlighting/themes/atelier-dune-dark.dart';
import 'package:flutter_highlighting/themes/atelier-dune-light.dart';
import 'package:flutter_highlighting/themes/atelier-estuary-dark.dart';
import 'package:flutter_highlighting/themes/atelier-estuary-light.dart';
import 'package:flutter_highlighting/themes/atelier-forest-dark.dart';
import 'package:flutter_highlighting/themes/atelier-forest-light.dart';
import 'package:flutter_highlighting/themes/atelier-heath-dark.dart';
import 'package:flutter_highlighting/themes/atelier-heath-light.dart';
import 'package:flutter_highlighting/themes/atelier-lakeside-dark.dart';
import 'package:flutter_highlighting/themes/atelier-lakeside-light.dart';
import 'package:flutter_highlighting/themes/atelier-plateau-dark.dart';
import 'package:flutter_highlighting/themes/atelier-plateau-light.dart';
import 'package:flutter_highlighting/themes/atelier-savanna-dark.dart';
import 'package:flutter_highlighting/themes/atelier-savanna-light.dart';
import 'package:flutter_highlighting/themes/atelier-seaside-dark.dart';
import 'package:flutter_highlighting/themes/atelier-seaside-light.dart';
import 'package:flutter_highlighting/themes/atelier-sulphurpool-dark.dart';
import 'package:flutter_highlighting/themes/atelier-sulphurpool-light.dart';
import 'package:flutter_highlighting/themes/atom-one-dark-reasonable.dart';
import 'package:flutter_highlighting/themes/atom-one-dark.dart';
import 'package:flutter_highlighting/themes/atom-one-light.dart';
import 'package:flutter_highlighting/themes/brown-paper.dart';
import 'package:flutter_highlighting/themes/codepen-embed.dart';
import 'package:flutter_highlighting/themes/color-brewer.dart';
import 'package:flutter_highlighting/themes/darcula.dart';
import 'package:flutter_highlighting/themes/dark.dart';
import 'package:flutter_highlighting/themes/default.dart';
import 'package:flutter_highlighting/themes/docco.dart';
import 'package:flutter_highlighting/themes/dracula.dart';
import 'package:flutter_highlighting/themes/far.dart';
import 'package:flutter_highlighting/themes/foundation.dart';
import 'package:flutter_highlighting/themes/github-gist.dart';
import 'package:flutter_highlighting/themes/github.dart';
import 'package:flutter_highlighting/themes/gml.dart';
import 'package:flutter_highlighting/themes/googlecode.dart';
import 'package:flutter_highlighting/themes/gradient-dark.dart';
import 'package:flutter_highlighting/themes/grayscale.dart';
import 'package:flutter_highlighting/themes/gruvbox-dark.dart';
import 'package:flutter_highlighting/themes/gruvbox-light.dart';
import 'package:flutter_highlighting/themes/hopscotch.dart';
import 'package:flutter_highlighting/themes/hybrid.dart';
import 'package:flutter_highlighting/themes/idea.dart';
import 'package:flutter_highlighting/themes/ir-black.dart';
import 'package:flutter_highlighting/themes/isbl-editor-dark.dart';
import 'package:flutter_highlighting/themes/isbl-editor-light.dart';
import 'package:flutter_highlighting/themes/kimbie.dark.dart';
import 'package:flutter_highlighting/themes/kimbie.light.dart';
import 'package:flutter_highlighting/themes/lightfair.dart';
import 'package:flutter_highlighting/themes/magula.dart';
import 'package:flutter_highlighting/themes/mono-blue.dart';
import 'package:flutter_highlighting/themes/monokai-sublime.dart';
import 'package:flutter_highlighting/themes/monokai.dart';
import 'package:flutter_highlighting/themes/night-owl.dart';
import 'package:flutter_highlighting/themes/nord.dart';
import 'package:flutter_highlighting/themes/obsidian.dart';
import 'package:flutter_highlighting/themes/ocean.dart';
import 'package:flutter_highlighting/themes/paraiso-dark.dart';
import 'package:flutter_highlighting/themes/paraiso-light.dart';
import 'package:flutter_highlighting/themes/pojoaque.dart';
import 'package:flutter_highlighting/themes/purebasic.dart';
import 'package:flutter_highlighting/themes/qtcreator_dark.dart';
import 'package:flutter_highlighting/themes/qtcreator_light.dart';
import 'package:flutter_highlighting/themes/railscasts.dart';
import 'package:flutter_highlighting/themes/rainbow.dart';
import 'package:flutter_highlighting/themes/routeros.dart';
import 'package:flutter_highlighting/themes/school-book.dart';
import 'package:flutter_highlighting/themes/shades-of-purple.dart';
import 'package:flutter_highlighting/themes/solarized-dark.dart';
import 'package:flutter_highlighting/themes/solarized-light.dart';
import 'package:flutter_highlighting/themes/sunburst.dart';
import 'package:flutter_highlighting/themes/tomorrow-night-blue.dart';
import 'package:flutter_highlighting/themes/tomorrow-night-bright.dart';
import 'package:flutter_highlighting/themes/tomorrow-night-eighties.dart';
import 'package:flutter_highlighting/themes/tomorrow-night.dart';
import 'package:flutter_highlighting/themes/tomorrow.dart';
import 'package:flutter_highlighting/themes/vs.dart';
import 'package:flutter_highlighting/themes/vs2015.dart';
import 'package:flutter_highlighting/themes/xcode.dart';
import 'package:flutter_highlighting/themes/xt256.dart';
import 'package:flutter_highlighting/themes/zenburn.dart';

const THEMES = {
  'a11y-dark': a11yDarkTheme,
  'a11y-light': a11yLightTheme,
  'agate': agateTheme,
  'an-old-hope': anOldHopeTheme,
  'androidstudio': androidstudioTheme,
  'arduino-light': arduinoLightTheme,
  'arta': artaTheme,
  'ascetic': asceticTheme,
  'atelier-cave-dark': atelierCaveDarkTheme,
  'atelier-cave-light': atelierCaveLightTheme,
  'atelier-dune-dark': atelierDuneDarkTheme,
  'atelier-dune-light': atelierDuneLightTheme,
  'atelier-estuary-dark': atelierEstuaryDarkTheme,
  'atelier-estuary-light': atelierEstuaryLightTheme,
  'atelier-forest-dark': atelierForestDarkTheme,
  'atelier-forest-light': atelierForestLightTheme,
  'atelier-heath-dark': atelierHeathDarkTheme,
  'atelier-heath-light': atelierHeathLightTheme,
  'atelier-lakeside-dark': atelierLakesideDarkTheme,
  'atelier-lakeside-light': atelierLakesideLightTheme,
  'atelier-plateau-dark': atelierPlateauDarkTheme,
  'atelier-plateau-light': atelierPlateauLightTheme,
  'atelier-savanna-dark': atelierSavannaDarkTheme,
  'atelier-savanna-light': atelierSavannaLightTheme,
  'atelier-seaside-dark': atelierSeasideDarkTheme,
  'atelier-seaside-light': atelierSeasideLightTheme,
  'atelier-sulphurpool-dark': atelierSulphurpoolDarkTheme,
  'atelier-sulphurpool-light': atelierSulphurpoolLightTheme,
  'atom-one-dark-reasonable': atomOneDarkReasonableTheme,
  'atom-one-dark': atomOneDarkTheme,
  'atom-one-light': atomOneLightTheme,
  'brown-paper': brownPaperTheme,
  'codepen-embed': codepenEmbedTheme,
  'color-brewer': colorBrewerTheme,
  'darcula': darculaTheme,
  'dark': darkTheme,
  'default': defaultTheme,
  'docco': doccoTheme,
  'dracula': draculaTheme,
  'far': farTheme,
  'foundation': foundationTheme,
  'github-gist': githubGistTheme,
  'github': githubTheme,
  'gml': gmlTheme,
  'googlecode': googlecodeTheme,
  'gradient-dark': gradientDarkTheme,
  'grayscale': grayscaleTheme,
  'gruvbox-dark': gruvboxDarkTheme,
  'gruvbox-light': gruvboxLightTheme,
  'hopscotch': hopscotchTheme,
  'hybrid': hybridTheme,
  'idea': ideaTheme,
  'ir-black': irBlackTheme,
  'isbl-editor-dark': isblEditorDarkTheme,
  'isbl-editor-light': isblEditorLightTheme,
  'kimbie.dark': kimbieDarkTheme,
  'kimbie.light': kimbieLightTheme,
  'lightfair': lightfairTheme,
  'magula': magulaTheme,
  'mono-blue': monoBlueTheme,
  'monokai-sublime': monokaiSublimeTheme,
  'monokai': monokaiTheme,
  'night-owl': nightOwlTheme,
  'nord': nordTheme,
  'obsidian': obsidianTheme,
  'ocean': oceanTheme,
  'paraiso-dark': paraisoDarkTheme,
  'paraiso-light': paraisoLightTheme,
  'pojoaque': pojoaqueTheme,
  'purebasic': purebasicTheme,
  'qtcreator_dark': qtcreatorDarkTheme,
  'qtcreator_light': qtcreatorLightTheme,
  'railscasts': railscastsTheme,
  'rainbow': rainbowTheme,
  'routeros': routerosTheme,
  'school-book': schoolBookTheme,
  'shades-of-purple': shadesOfPurpleTheme,
  'solarized-dark': solarizedDarkTheme,
  'solarized-light': solarizedLightTheme,
  'sunburst': sunburstTheme,
  'tomorrow-night-blue': tomorrowNightBlueTheme,
  'tomorrow-night-bright': tomorrowNightBrightTheme,
  'tomorrow-night-eighties': tomorrowNightEightiesTheme,
  'tomorrow-night': tomorrowNightTheme,
  'tomorrow': tomorrowTheme,
  'vs': vsTheme,
  'vs2015': vs2015Theme,
  'xcode': xcodeTheme,
  'xt256': xt256Theme,
  'zenburn': zenburnTheme,
};
